### ISSUE TITLE
Prefix classes and ids

### ISSUE THREAD

**Issue by victorlevasseur** [scttcper/ngx-toastr#128]
Hi,

In my company project, we use both materializecss and your library. Unfortunately, they share the same classe (.toast) and id (#toast-container). So, it's causing some styling problems (missing background colors, toast always to the top-right corner despite setting the positionClass to put them in the middle...).

Is it possible to add prefixes to the classes and ids used by your library to fix the conflict?

**Comment by scttcper** [comment]
Pass a `toastClass` to your global config to add your own prefix! https://github.com/scttcper/ngx-toastr#toastrconfig-global-options

Copy the css out and make your changes. https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr.css

Edit: Oh i see #toast-container is also used.... That's seems weird.

Are you using sass? Instead of importing entire materialize css you should copy and paste the https://github.com/Dogfalo/materialize/blob/master/sass/materialize.scss scss file (edit the paths) and comment out the toast file from being imported. You can also shrink the css by removing other things you aren't using.

**Comment by victorlevasseur** [comment]
Yes, that's exactly what I ended up doing. Thanks for your help.
