### ISSUE TITLE
Changing the configuration of iconClasses seems not to work via forRoot but only via injection

### ISSUE THREAD

**Issue by bseiller** [scttcper/ngx-toastr#131]
First of all: Very nice piece of software!
Now what confused me:

```javascript
ToastrModule.forRoot(
      {
        iconClasses: {
          error: 'toast-error-ABC'
        }
      }
    )
```
does not work as expected - keeps the default value 'toast-error'
as can be seen in src/app.ts here:
https://embed.plnkr.co/ABCkco3p3JYYeBEXxiNA/

```javascript
export class AppModule {
  constructor(toastrConfig: ToastrConfig) {
    toastrConfig.iconClasses.error = 'toast-error-ABC';
  }
}
```

works just fine - the default value is replaced with 'test-error-ABC'
as can be seen in src/app.ts here:
https://embed.plnkr.co/MQa4myRfs4GotrnOlLrZ/

If the first example can't work/is intentionally a little hint in the section "Override default settings" could save others some headscratching.

Cheers

**Comment by yarrgh** [comment]
Just quickly looking through the source. I believe the issue happens at [https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr-config.ts#L92-L95](https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr-config.ts#L92-L95)

The statements should probably be reversed so that it uses the passed in value, if it exists, instead of if the class property has a value (which is always true). I can't make a pull request until a bit later so if there still isn't one open I'll go ahead and open one when I'm able.

**Comment by scttcper** [comment]
🚀  https://github.com/scttcper/ngx-toastr/releases/tag/5.2.4
