### ISSUE TITLE
Error: No provider for InjectionToken ToastConfig!

### ISSUE THREAD

**Issue by anmary** [scttcper/ngx-toastr#193]
Hello,

Thanks for your great work.

I'm trying to test a component which uses toastr. I declared ToastrService as a provider but I'm running in the following error when I run my tests, "Error: No provider for InjectionToken ToastConfig!".

What can I do to fix my test ? 

Thanks.

**Comment by anmary** [comment]
I added ToastrService, TOAST_CONFIG and Overlay as providers and it seems to work fine. Thanks.

**Comment by yarrgh** [comment]
You should import the ToastrModule into your AppModule just as it says in the ReadMe. It takes care of providing all the necessary services for you

**Comment by anmary** [comment]
I have no problem using the module when I'm serving the application, the problem on which I stumbled on was only occurring during testing.

**Comment by xmeng1** [comment]
must use `ToastrModule.forRoot(), // ToastrModule added` in AppModule
(I try to import it to other modules, such as SharedModule, it will get this error.

**Comment by yarrgh** [comment]
`forRoot()` should only be used in AppModule or something like a Core module where it is only used one for your entire application. This is because certain services and classes should only be provided once. 

If you need access to the ToastComponent from another module you can import ToastrModule (without `forRoot()`) in something like a SharedModule.

**Comment by Jelledb** [comment]
The docs are incorrect. You always need to use forRoot().
Using .forRoot() fixed the issue for me.
