### ISSUE TITLE
OpaqueToken error

### ISSUE THREAD

**Issue by HaakonH** [scttcper/ngx-toastr#253]
I'm getting this error now that I have updated to angular 5:

ERROR in node_modules/toastr-ng2/toastr-module.d.ts(1,31): error TS2305: Module '"C:/projects/email/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by scttcper** [comment]
dupe #242 Update to the latest version of ngx-toastr. The latest version 6.5.0 doesn't use OpaqueToken (removed from Angular 5)

Uninstall toastr-ng2. That is the old package name and shouldn't be used anymore. It has since been renamed to ngx-toastr.

Install ngx-toastr@latest which should solve your issue.
