### ISSUE TITLE
Circular dependency when used in APP_INITIALIZER

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [scttcper/ngx-toastr#328]
If you inject ToastrService as a dependency to an object created during APP_INITIALIZER, the compiler complains about circular dependencies. I was wondering if that is expected behavior and what Toastr possibly can depend upon, that blocks instantiation.

The obvious solution is to inject Injector and then use it later in the lifecycle of that class to retrieve ToastrService (which works fine, even with setTimeout), but seems a bit hacky.

**Comment by scttcper** [comment]
Possibly the injector? https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr.service.ts#L56

**Comment by sebastian-zarzycki-es** [comment]
I think injector is ready at that point of lifecycle.

**Comment by yarrgh** [comment]
Might be the overlay. It depends on both the ApplicationRef and ComponentFactoryResolver which may not be available at the time the app is initializing. Not sure though.

This same "hack" needs to be done if using ToastrService in an error handler. Some dependency isn't available that early in the lifecycle and requires it to be injected at a later point.

While not ideal, there isn't much that can be done at the moment. This may or may not change if/when we move to `@angular/cdk` instead of our own customized portal/overlay.

**Comment by maybeec** [comment]
Any update on that? Any workaround, which could be applied besides removing all providers, which depend on toastr and are setup as APP_INITIALIZER?

**Comment by sebastian-zarzycki-es** [comment]
I was under impression that it worked fine for previous versions and Angular 8, but now, on Angular 9, and toastr on 12.0.0, this returned again.

Should be reopened?

**Comment by philonor** [comment]
Happens to us in Angular **9** when providing an `ErrorHandler` with dependency on `toastr`.
```
@NgModule({
  ..
  providers: [
    {provide: ErrorHandler, useClass: SomeHandler}
  ]
});
export class AppModule {}

@Injectable() 
export class SomeHandler extends ErrorHandler {
  
  constructor (private toastr: ToastrService) {}

}
```

**Comment by emanuel-virca** [comment]
Faced the same issue, managed to fix it by using the following solution: [https://github.com/scttcper/ngx-toastr/issues/179#issuecomment-325724269]https://github.com/scttcper/ngx-toastr/issues/179#issuecomment-325724269)
