### ISSUE TITLE
no mixin named border-radius

### ISSUE THREAD

**Issue by oscarlagatta** [scttcper/ngx-toastr#336]
Hi, any more details of how to include the toastr-bs4-alert.scss in an angular-cli project ? 
Thank you , great tool.

**Comment by yarrgh** [comment]
In order to use the toastr-bs4-alert.scss you have to be using scss in your angular-cli project and have to import the bootstrap scss files before the toastr-bs4-alert.scss

```
If you are using sass you can import the css.
@import "~ngx-toastr/toastr";
// or import a bootstrap 4 alert styled design (SASS ONLY)
// should be after your bootstrap imports, it uses bs4 variables
@import "~ngx-toastr/toastr-bs4-alert"
```

In the demo app, you can see that the `toastr-bs4-alert` is imported into the `styles.scss` file after all of the bootstrap scss imports:
https://github.com/scttcper/ngx-toastr/blob/04e8339cb1c4923259dc3162591ab3c7dbb0dfa4/src/styles.scss#L45

**Comment by oscarlagatta** [comment]
Thanks Trevor, much appreciated will investigate a bit more.

**Comment by brayanL** [comment]
It's necessary to install bootstrap 4 if you install bootstrap 5 you will see that kind of error.
