### ISSUE TITLE
How to use ngx-toastr in a private variable?

### ISSUE THREAD

**Issue by netdjw** [scttcper/ngx-toastr#607]
Hi!

I have this code in `app-error-handler.ts` file:

```
import { ErrorHandler } from '@angular/core';
import { ToastrService } from 'ngx-toastr';

export class AppErrorHandler implements ErrorHandler {
  private toastr: ToastrService;

  handleError(error: any) {
    if ( error.msg !== undefined) {
      this.toastr.error('Here is the error message: ' + error.msg + '<br>Details in console log', 'Error',
        { enableHtml: true, timeOut: 10000, closeButton: true, positionClass: 'toast-bottom-center', tapToDismiss: true });
    }
    console.error(error.originalError);
  }
}
```

And I get this error message:

```
Uncaught TypeError: Cannot read property 'error' of undefined
    at AppErrorHandler.push../src/app/shared/error/app-error-handler.ts.AppErrorHandler.handleError (app-error-handler.ts:9)
```

The 9. line is started with `this.toastr.error(...`

Is there any way to define the `this.toastr` variable without consturctor?

**Comment by yarrgh** [comment]
From the code you've provided, it doesn't look like your toastr property ever gets initialized. 

The only way to get a reference to the `ToastrService` is via Dependency Injection. You have to, at least, inject the `Injector` service into your error handler via constructor and then use the `Injector` to get a reference to the `ToastrService`. See https://github.com/scttcper/ngx-toastr/issues/179#issuecomment-325724269

The reasoning is because `ToastrService` has dependencies that it needs itself. The easiest way is to let Dependency Injection take care of all it for you. You could initialize `ToastrService` yourself and but you'd have to provide it with all of its dependencies yourself. That's very tedious and any setting you've overridden in the `ToastrModule.forRoot()` function wouldn't get applied.
