### ISSUE TITLE
How to create a full width inline toast

### ISSUE THREAD

**Issue by komyg** [scttcper/ngx-toastr#622]
Hi,

I wonder if it is possible to create a Toast that is inline but also extends to the full width of the inline container.

I've tried to add both styles, but then the Toast disappeared.

```
  this.toastConfig = {
      closeButton: true,
      disableTimeOut: true,
      toastComponent: OnyoMktToastComponent,
      positionClass: 'inline toast-top-full-width',
      preventDuplicates: true
    };
```

I also tried to create a custom toast and add `width: 100%` to it, but that also didn't work.

Can anyone help me? Or point me in the right direction?

**Comment by pedropagotto** [comment]
Hi Komyg!

first check using your browser's element inspector which css toastr is being assigned, secondly I would suggest you remove the import of the default css class from lib ngx-toastr and within the style.cs of your angular application to copy the default class da lib ngx-toastr so that you can customize the properties you require.

You can find the complete css code for customization in this link

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr.css#L136-L141

I went through a similar problem recently and I performed this procedure and it worked
