### ISSUE TITLE
feature request: easy access to toastType from toast

### ISSUE THREAD

**Issue by Gryxis** [scttcper/ngx-toastr#700]
Hi there!
I try to use a custom Toast via the new Component.
There I need to know what type of toast it is, e.g. if it is a success, info ,error or warning toast.
This information lies hidden in the toastrpackage.
Since I am not sure if every Toast has its own toastrpackage I suggest the Toastrcomponent to hold its config and information.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr-config.ts#L148-L164

it has types and is not hidden

**Comment by Gryxis** [comment]
The toast itself does not have types. It has an injected ToastPackage but I do not fully understand what a ToastPackage represents.
[ToastComponent](https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast.component.ts)

**Comment by Kalpesh300** [comment]
> Hi there!
> I try to use a custom Toast via the new Component.
> There I need to know what type of toast it is, e.g. if it is a success, info ,error or warning toast.
> This information lies hidden in the toastrpackage.
> Since I am not sure if every Toast has its own toastrpackage I suggest the Toastrcomponent to hold its config and information.

Same issue. How to modify the theme of custom toast according to the type( success, error, ... ) of toast?

One way to accomplish this is to add classes of toast-\<type>( toast-success, toast-error... ) to `.toast-container` element instead of `.ngx-toastr` element. But that is dependent on the library. 

One quick solution is to create a custom wrapper service - `CustomToastrService`. 
This service will have the same methods as `ToastrService` but with an additional line to add type to the custom component.

**CustomToastrService**
```
success(message, title ) {
    const activeToast = toastrService.success(message, title);
    activeToast.toastRef.componentInstance.type = 'success';
}
```
You can now use the value of `type` property in the custom component.

**Comment by scttcper** [comment]
Its already available https://github.com/scttcper/ngx-toastr/blob/c2b4e2c797a5eb6e09c729964712da18b015dfa0/src/lib/toastr/toastr-config.ts#L157 `this.toastPackage.toastType`
